title: Let's learn some basics
author: Gonzalo García  
email: gsg.c1389@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I don't have a website yet, but the time will come.

# social links
twitter_username: #
github_username:  #

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
